trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: matrix
    strategy:
      matrix:
        Job1:
          name: One
        Job2:
          name: Two
        Job3:
          name: Three
    steps:
      - script: ./test.py "$(name)"
