trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: Check
    dependsOn: []
    jobs:
      - job: Lint
        steps:
          - script: echo Hi
            displayName: Hi
  - stage: Local
    dependsOn:
      - Check
    jobs:
      - job: Test
        steps:
          - script: echo Hi
            displayName: Hi
  - stage: Remote
    dependsOn:
      - Local
    jobs:
      - template: templates/build.yml
        parameters:
          remotes:
            - name: RHEL 8.5
              code: rhel/8.5,python=3.9
            - name: Ubuntu 22.04
              code: ubuntu/22.04
          architectures:
            - x86_64
            - aarch64
