trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: init
    steps:
      - script: ./init.py
        name: init_matrix
  - job: matrix
    dependsOn: init
    strategy:
      matrix:
        J001:
          name: "Job #001"
        J002:
          name: "Job #002"
        J003:
          name: "Job #003"
        J004:
          name: "Job #004"
        J005:
          name: "Job #005"
    steps:
      - script: ./test.py "$(name)"
