trigger:
  batch: true
  branches:
    include:
      - master

pr:
  autoCancel: true
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: init
    steps:
      - script: ./init.py
        name: init_matrix
  - job: matrix
    dependsOn: init
    strategy:
      matrix: $[ dependencies.init.outputs['init_matrix.config'] ]
    steps:
      - script: ./test.py "$(name)" "$(download)"
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'results/*.xml'
          mergeTestResults: True
          failTaskOnFailedTests: True
          publishRunAttachments: True
