trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Job One
    steps:
      - script: echo One
        displayName: Name One
  - job: Job Two
    steps:
      - script: echo Two
        displayName: Name Two
