trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: Check
    dependsOn: []
    jobs:
      - job: Lint
        steps:
          - script: echo pip install -r test/requirements/nox.txt --disable-pip-version-check --user
            displayName: Install nox
          - script: echo nox
            displayName: Run linters using nox
  - stage: Local
    dependsOn:
      - Check
    jobs:
      - job: Test
        steps:
          - script: echo pip install -r test/requirements/nox.txt --disable-pip-version-check --user
            displayName: Install nox
          - script: echo nox -e pytest -- -m 'not remote and not credentials'
            displayName: Run pytest using nox
  - stage: Remote
    dependsOn:
      - Local
    jobs:
      - template: templates/build.yml
        parameters:
          remotes:
            - name: RHEL 8.5
              code: rhel/8.5,python=3.9
            - name: Ubuntu 22.04
              code: ubuntu/22.04
          architectures:
            - x86_64
            - aarch64
