trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Start
    steps:
      - script: echo Start
  - job: T1
    steps:
      - script: echo T1
    dependsOn: Start
  - job: T2
    steps:
      - script: echo T2
    dependsOn: Start
  - job: Stop
    steps:
      - script: echo Stop
    dependsOn:
      - T1
      - T2
