trigger:
  batch: true
  branches:
    include:
      - main

pr:
  autoCancel: true
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-22.04'

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:3.0.0

variables:
  - name: defaultContainer
    value: quay.io/ansible/azure-pipelines-test-container:3.0.0

jobs:
  - job: new
    containerResource: default
    steps:
      - script: echo Hello World
        displayName: Hello World

